apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-booking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-booking-backend
  template:
    metadata:
      labels:
        app: movie-booking-backend
    spec:
      containers:
        - name: movie-booking-backend
          image: premaravind147/movie-booking-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
